version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
      
  frontend:
      build:
        context: ./front-end
      container_name: react-frontend
      ports:
        - '3000:3000'
      volumes:
        - ./front-end:/app
      depends_on:
        - web
      networks:
        - app_network

networks:
  app_network:
    driver: bridge


volumes:
  postgres_data:
